import React, { useEffect } from 'react';
import { Shield, ChevronLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function PrivacyPolicy() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div style={{ paddingBottom: '100px' }}>
      <div style={{ padding: '80px 0 100px 0', textAlign: 'center', position: 'relative' }}>
        <div className="container" style={{ position: 'relative', zIndex: 2 }}>
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '24px' }}>
            <div style={{ background: 'rgba(79, 70, 229, 0.2)', padding: '20px', borderRadius: '50%', border: '1px solid rgba(79, 70, 229, 0.5)', boxShadow: '0 0 30px rgba(79, 70, 229, 0.3)' }}>
              <Shield size={48} color="#A5B4FC" />
            </div>
          </div>
          <h1 style={{ fontSize: '3.5rem', marginBottom: '16px', fontWeight: 800, letterSpacing: '-1px' }}>Privacy Policy</h1>
          <p style={{ margin: 0, fontSize: '1.1rem', color: 'var(--text-muted)' }}>Last updated: May 1, 2026</p>
        </div>
      </div>

      <div className="privacy-container">
        <Link to="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', marginBottom: '32px', color: 'var(--text-muted)', fontWeight: 500 }}>
          <ChevronLeft size={20} /> Back to Home
        </Link>
        
        <div className="privacy-section">
          <h3>1. Introduction</h3>
          <p>
            PaperEval ("we", "our", or "us") is committed to protecting your privacy. This
            Privacy Policy explains how we collect, use, and safeguard your information when
            you use our mobile application PaperEval (the "App"). By using the App, you
            agree to the terms of this policy.
          </p>
        </div>

        <div className="privacy-section">
          <h3>2. Information We Collect</h3>
          <p>We collect the following types of information:</p>
          <ul>
            <li><strong>Account Information:</strong> Email address and password (hashed) when you register.</li>
            <li><strong>Uploaded Images:</strong> Photos of answer sheets and question papers that you upload for evaluation. These images are processed by our AI system to perform grading and are stored temporarily on our servers and optionally on Cloudinary for displaying evaluation history.</li>
            <li><strong>Evaluation Data:</strong> Scores, question-by-question results, and notes generated by our AI evaluation pipeline.</li>
            <li><strong>Device Information:</strong> Basic platform information (Android version) used to optimise the app experience. We do not collect device IDs or unique hardware identifiers.</li>
          </ul>
        </div>

        <div className="privacy-section">
          <h3>3. How We Use Your Information</h3>
          <p>We use your information solely to:</p>
          <ul>
            <li>Provide and improve the evaluation service.</li>
            <li>Authenticate your account securely.</li>
            <li>Store your evaluation history so you can access it later.</li>
            <li>Generate downloadable PDF reports of your evaluations.</li>
          </ul>
          <p>We do NOT use your data for advertising, profiling, or sell it to any third parties.</p>
        </div>

        <div className="privacy-section">
          <h3>4. Data Storage & Security</h3>
          <ul>
            <li>Your account credentials are stored in a MongoDB database hosted on a secure cloud provider. Passwords are never stored in plain text — they are hashed using bcrypt.</li>
            <li>Uploaded images are transmitted over HTTPS and processed on our backend server. Images may be stored on Cloudinary solely to display them in your evaluation history.</li>
            <li>We use industry-standard security measures including JWT-based authentication with token expiration.</li>
          </ul>
        </div>

        <div className="privacy-section">
          <h3>5. Third-Party Services</h3>
          <p>The App relies on the following third-party services:</p>
          <ul>
            <li><strong>OpenAI API / Gemini API:</strong> Used for AI-powered evaluation of answer sheets. Images and text are sent for processing in accordance with their privacy policies.</li>
            <li><strong>Cloudinary:</strong> Used for image storage and delivery for evaluation history.</li>
            <li><strong>Render.com:</strong> Cloud hosting provider for our backend API.</li>
            <li><strong>MongoDB Atlas:</strong> Cloud database for storing user accounts and evaluation records.</li>
          </ul>
        </div>

        <div className="privacy-section">
          <h3>6. Data Retention & Deletion</h3>
          <ul>
            <li>Evaluation history is retained as long as your account is active.</li>
            <li>You can delete individual evaluations from within the app at any time.</li>
            <li>To request full account deletion and removal of all your personal data, you can contact us at <strong>learncas@gmail.com</strong>. We will process your deletion request within 30 days.</li>
          </ul>
        </div>

        <div className="privacy-section">
          <h3>7. Children's Privacy</h3>
          <p>
            The App is not directed at children under the age of 13. We do not knowingly
            collect personal information from children under 13. If you believe a child has
            provided us personal information, please contact us immediately.
          </p>
        </div>

        <div className="privacy-section">
          <h3>8. Your Rights</h3>
          <p>Depending on your location, you may have the following rights regarding your data:</p>
          <ul>
            <li>Right to access the personal data we hold about you.</li>
            <li>Right to correct inaccurate information.</li>
            <li>Right to request deletion of your data.</li>
            <li>Right to data portability.</li>
          </ul>
          <p>To exercise any of these rights, contact us at learncas@gmail.com.</p>
        </div>

        <div className="privacy-section">
          <h3>9. App Permissions</h3>
          <p>To provide our grading services, the App may request the following permissions:</p>
          <ul>
            <li><strong>Camera:</strong> To take photos of answer sheets for evaluation.</li>
            <li><strong>Photo Gallery:</strong> To upload existing photos of papers from your device.</li>
            <li><strong>Storage:</strong> To save generated PDF evaluation reports to your device.</li>
          </ul>
        </div>

        <div className="privacy-section">
          <h3>10. Contact Us</h3>
          <p>
            If you have any questions or concerns about this Privacy Policy, please contact
            us at <strong>learncas@gmail.com</strong>.
          </p>
        </div>
      </div>
    </div>
  );
}
